### PR TITLE
v2.0.0

### PR DESCRIPTION
**Pull request by m-mohr**
Open issues:
- [x] Some slots may need additional props (tbc by @christophfriedrich)
- [x] The Map in Collection (not Collections!) view is distorted in a Jupyter env
- [x] StacUtils should be replaced with @radiantearth/stac-fields
- [x] I had it in the recent demo that expanding a Process in the Processes component took some time. During that time it said "No data available" although it seems to just be loading or so. Expanding twice again and then it showed up. Either an issue with slow connections or something different.
- [ ] Common parts (i.e. utils.js, maybe Loading.vue/Errored.vue) should not be included multiple times
- [ ] ~Check whether https://github.com/karol-f/vue-custom-element/ instead of the native vue-cli method gives better results~ not yet
- [x] Check issue that with slow connection and WC the innerHTML is empty
- [x] Leaflet.css gives an error in Web Editor/Hub when building. Probably needs another way of importing it in vue-components. Check whether other <style src="..."> imports work as expected.

### CODE REVIEW

**Comment by m-mohr** [comment]
Both vue-custom-elemt and the native vue-cli wrapper have their pros and cons.

vue-cli-wrapper is easier to use, but seems not maintained any longer. Also, it doesn't allow me to specify custom parts that are not included in every component bundle. vue-cli-wrapper has some bugs, e.g. 
* https://github.com/vuejs/vue-cli/issues/6225 (workaround implemented)
* issues with boolean prop casting values, see https://github.com/vuejs/vue-web-component-wrapper/pull/58 (workaround implemented)

vue-custom-element has other issues:
* ejects the files with a .umd in the filenames (see https://stackoverflow.com/questions/66050863/vue-cli-remove-umd-from-filename-in-dist-folder)
* shadow DOM is more complicated to set up
* props need to be specified in main.js (?)
* async doesn't work properly yet (?)

Reading objects from the script tags seems to have a bug in slow environments in general (see above).

**Comment by m-mohr** [comment]
@christophfriedrich Ready for review/merge

**Comment by christophfriedrich** [comment]
Thanks for letting me know, I'll look through it!

**Review by christophfriedrich — APPROVED** [review]
I tried it out in the Hub and, with the appropriate adaptations, had no issues whatsoever
:arrow_right: I approve for the Hub :+1: 

I also double-checked that everything mentioned in the Changelog is also included in the documentation (i.e. Readme), which is the case now, so other dependents shouldn't have troubles either when they convert from 1.0.x to 2.0.0.
:arrow_right: I approve in general too :+1:

**Pull request merged**
